name: Compilar APK Antigravity
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Esto le permite activar la compilación manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Descargar Código del Repositorio
      uses: actions/checkout@v4

    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias del Sistema Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev lld openjdk-17-jdk zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Ejecutar Compilación con Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug
      env:
        BUILDOZER_ALLOW_KIVY_NEW_DESIGNER: 1

    - name: Guardar y Subir el APK Generado
      uses: actions/artifacts@v4
      with:
        name: AntiSpyware-APK
        path: bin/*.apk
